# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 's2i-clojure'
  dockerId: sosoaDockerRegistry

steps:
- script: docker build -t $(dockerId).azurecr.io/$(imageName) .
  displayName: 'Build docker image'

- script: |
   docker login -u $(dockerId) -p $PSWD $(dockerId).azurecr.io
   docker push $(dockerId).azurecr.io/$(imageName)
  displayName: pushing docker image to docker container registry
  env:
    PSWD: $(dockerPassword)
