trigger:
- master

pool:
  name: 'mgAgentPool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ATALLC Docker Registry'
    repository: 's2i-clojure'
    tags: 'latest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'