trigger:
- master

stages:
- stage: BuildStage
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: 'Build job'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'atalld-acr-connection'
        repository: 's2i-clojure'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    - script: docker system prune -a -f
      displayName: Prune dangling Docker images