trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'SoSOA Docker Registry'
    repository: 's2i-clojure'
    tags: 'latest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'