trigger:
- master

stages:
- stage: BuildStage
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: 'Build job'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ATALLC Docker Registry'
        repository: 's2i-clojure'
        tags: 'latest'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'